import = ["~/.config/alacritty/onedark.toml", "~/.config/alacritty/font.toml"]

live_config_reload = true

[window]
padding = { x = 15, y = 15 }
decorations = "None"
opacity = 1.0
dynamic_title = true

[scrolling]
history = 10000
multiplier = 3

[bell]
animation = "Linear"
duration = 50
color = "#3f6566"
command = { program = "paplay", args = ["/usr/share/sounds/freedesktop/stereo/dialog-error.oga"] }

[selection]
save_to_clipboard = false

[cursor]
style = { shape = Block, blinking = Off }
vi_mode_style = { shape = Block, blinking = On }
blink_interval = 1000
blink_timeout = 0
unfocused_hollow = false

[mouse]
hide_when_typing = true