live_config_reload = true

[window]
padding = { x = 15, y = 15 }
decorations = "None"
opacity = 1.0
dynamic_title = true

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "JetBrainsMono NF"}
bold = { family = "JetBrainsMono NF"}
italic = { family = "JetBrainsMono NF"}
bold_italic = { family = "JetBrainsMono NF"}
size = 10

[colors.primary]
foreground = "#b8bfe5"
background = "#1f2329"

[colors.cursor]
cursor = "#465b80"
text = "#e5e5e5"

[colors.normal]
black = "#0f1319"
red = "#644d66"
green = "#375759"
yellow = "#736871"
blue = "#3f5273"
magenta = "#543f66"
cyan = "#324f66"
white = "#b3b3b3"

[colors.bright]
black = "#b3b3b3"
red = "#735771"
green = "#3f6566"
yellow = "#807476"
blue = "#465b80"
magenta = "#533969"
cyan = "#385a73"
white = "#e5e5e5"

[selection]
save_to_clipboard = false

[cursor]
style = { Block, On }
blink_interval = 550
unfocused_hollow = false