require("config.plugins-setup")
require("config.core.options")
require("config.core.keymaps")
require("config.core.colorscheme")
require("config.plugins.nvim-tree")
require("config.plugins.lualine")
require("config.plugins.colorizer")